image: wukl/brufs-ci

stages:
  - test-library
  - test-tools

.test-any:
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBRUFS_SANITIZE=OFF

test:libbrufs:
  stage: test-library
  extends: .test-any
  except:
    - schedules
  script:
    - make libbrufs-test -j16
    - libbrufs/libbrufs-test
    - make libbrufs-coverage
  artifacts:
    paths:
      - build/libbrufs/libbrufs.a
      - build/coverage
    expire_in: 1 week

test:brufscli:
  stage: test-tools
  extends: .test-any
  except:
    - schedules
  dependencies:
    - test:libbrufs
  script:
    - make brufscli-exe -j16
    - make brufscli-test -j16
    - brufscli/brufs version
    - brufscli/brufscli-test
    - make brufscli-coverage
  artifacts:
    paths:
      - build/coverage
    expire_in: 1 week

test:release:
  stage: test-tools
  only:
    - schedules
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j8
    - brufscli/brufs version
    - libbrufs/libbrufs-test
    - brufscli/brufscli-test
